#!/bin/sh

SDIR=`dirname $0`
. $SDIR/heatermeter.conf

stty -F $SERIAL_DEVICE $SERIAL_BAUD min 1 igncr

if [ ! -f "$RRD_FILE" ] ; then
  $SDIR/create_hm_rrd
fi

ln -s "$JSON_FILE" $SDIR/json
ln -s "$LOG_FILE" $SDIR/data.txt

CNT=999
IFS=$','

while read SP P0 P0A P1 P1A P2 P2A P3 P3A FI FA LID CRAP; do
    if [ -n "$LID" ] ; then
      TIME=`date +%s`

      cat << EOF > $JSON_FILE
{"time":$TIME, "temps":[{"n":"Pit","c":$P0,"a":$P0A},{"n":"Food Probe1","c":$P1,"a":$P1A},{"n":"Food Probe2","c":$P2,"a":$P2A},{"n":"Ambient","c":$P3,"a":$P3A},{}],"set":$SP,"lid":$LID,"fan":{"c":$FI,"a":$FA}}
EOF

      DATA=$SP:$P0:$P1:$P2:$P3
      CNT=$((CNT+1))
      if [ "$CNT" -eq 15 ] ; then
        CNT=0
        echo $TIME:$DATA:$FI:$LID >> $LOG_FILE
      fi
      
      if [ "$LID" -ne 0 ] ; then
        FI="-$LID"
      fi 

      rrdtool update $RRD_FILE N:$DATA:$FI
    fi
done < $SERIAL_DEVICE
