#!/bin/sh

. /etc/heatermeter.conf

# figure out where the first non NaN value is then use
# that to determine how much data is in the rrd
T=`date +%s`

if [ -n "$QUERY_STRING" ] ; then
  NANCNT=$QUERY_STRING
else
  T120=$((T/120*120))
  NANCNT=`$RRD fetch $RRD_FILE AVERAGE -s end-24h -e $T120 -r 180 |\
      fgrep -m1 -n e+ | cut -d":" -f1`
  if [ -z "$NANCNT" ] ; then
      NANCNT=480
  fi
fi

if [ $NANCNT -ge 460 ] ; then
  TD=10
  ST="AVERAGE -s end-1hr"
elif [ $NANCNT -ge 360 ] ; then
  TD=60
  ST="AVERAGE -s end-6hr"
elif [ $NANCNT -ge 240 ] ; then
  TD=120
  ST="AVERAGE -s end-12hr"
else
  TD=180
  ST="AVERAGE -s end-24hr"
fi

T=$((T/TD*TD))

if [ ! -f "$RRD_FILE" ] ; then 
    echo Status: 503 Database Unavailable
    echo Content-Type: text/plain
    echo
    echo No database: $RRD_FILE
    exit
fi

echo Content-Type: text/plain
echo Cache-Control: no-cache
#echo Content-Encoding: gzip
echo

if [ "$1" = "json" ] ; then
$RRD fetch $RRD_FILE $ST -r $TD -e $T |\
    awk 'BEGIN {OFS=","; FS="[: ]"; ORS=""; print "[";} \
	NR>2 {printf("[%s,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f]",$1,$3,$4,$5,$6,$7,$8)}\
         END {print "[]]";}'
else
$RRD fetch $RRD_FILE $ST -r $TD -e $T
fi

         #NR>2 {print "["$1,$3,$4,$5,$6,$7,$8"]" } \
