#!/bin/sh

# not used so just set to current
export ARDMK_DIR=.

if [ -z "$ARDUINO_DIR" ] ; then
  export ARDUINO_DIR=/C/Arduino/Arduino-1.0
  export ARDUINO_DIR=/C/Arduino/src/build/windows/work
fi

# Make sure the Arduino utilities are in the path
ARDUINO_BIN=${ARDUINO_DIR}/hardware/tools/avr/utils/bin
case ":$PATH:" in
  *":$ARDUINO_BIN:"*);;
  *) PATH="$ARDUINO_BIN:$PATH";;
esac

${ARDUINO_BIN}/make $*
