#!/bin/sh

HEX="/tmp/hm.hex"
if [ -n "$1" ] ; then
  HEX="$1"
fi

if [ ! -f "$HEX" ] ; then
  echo No input file $HEX
  exit 1
fi

echo -n "Stopping LinkMeter "
lua /usr/lib/lua/lmclient.lua LMD0

SERIAL_DEVICE=`uci get lucid.linkmeter.serial_device`
SERIAL_BAUD=`uci get lucid.linkmeter.serial_baud`
stty -F $SERIAL_DEVICE $SERIAL_BAUD 2>&1

CNT=0
while [ "$CNT" -lt 2 ] ; do
    echo -e \\n/reboot > $SERIAL_DEVICE

    avrdude -pm328p -carduino -P$SERIAL_DEVICE \
      -V -D -Uflash:w:$HEX:i 2>&1

    if [ $? -eq 0 ] ; then
      echo LM Success
      rm $HEX
      CNT=999
    else
      echo Failed attempt $CNT
    fi

    CNT=$((CNT+1))
done 

echo -n "Starting LinkMeter "
lua /usr/lib/lua/lmclient.lua LMD1
