#!/bin/sh /etc/rc.common
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=linkmeterd
DESC="LinkMeter/HeaterMeter Service"
START=99

test -x $DAEMON || exit 0
set -e

start() {
	echo -n "Starting $DESC: $NAME"
	lua -llinkmeterd -e 'linkmeterd.start()'
	echo "."
}

stop() {
	echo -n "Stopping $DESC: $NAME"
	lua -llinkmeterd -e 'linkmeterd.stop()'
	echo "."
}

restart() {
	stop
	sleep 1
	start
}

reload() {
	restart
}
