#!/bin/sh /etc/rc.common

NAME=linkmeterd
DESC="LinkMeter/HeaterMeter Service"
START=99

USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command lua -llinkmeterd -e 'linkmeterd.start()'
  procd_add_mdns "http" "tcp" "80" "path=/cgi-bin/luci/lm/"
  procd_close_instance
}
