#!/bin/sh /etc/rc.common

NAME=linkmeterd
DESC="LinkMeter/HeaterMeter Service"
START=99

USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command lua -llinkmeterd -e 'linkmeterd.start()'
  #procd_add_mdns "https" "tcp" "443" "path=/luci/lm/"
  procd_add_mdns "http" "tcp" "80" "path=/luci/lm/"

  # procd_add_mdns doesn't have a way to set the instance name so manually
  # add data.mdns.http_80.instance to use instead of $HOSTNAME._http._tcp.$HOSTNAME.local
  local old_cb
  json_set_namespace procd old_cb
  json_select "data"
    json_select "mdns"
      json_select "http_80"
      json_add_string "instance" "HeaterMeter on $HOSTNAME"
      json_select ..
    json_select ..
  json_set_namespace $old_cb

  procd_close_instance
}
